### ISSUE TITLE
how to run url in background 

### ISSUE THREAD

**Issue by sunsgs** [zlargon/google-tts#1]
What if i want to execute node file.js and listen to the output?

**Comment by sunsgs** [comment]
Hi, i have executed the example on the main page, i have in the console log the url, can i listen directly without to copy and paste the url ?

**Comment by zlargon** [comment]
Oh, I see. You would like to listen to the "audio" directly, right?

At first, you have to download the audio as a MP3 file by the URL.
Then, use the external "command line" to play the MP3 audio file.

You may execute different command line of audio player on different platforms, such as using command line `afplay` on macOS, `mpg123` on Linux, and `dlc` on Windows.

You can also check out this repo.
https://github.com/zlargon/voc

Hope this will be helpful to you. 😃

**Comment by sunsgs** [comment]
Do you have also the library speech to text? so i can record an audio and have it as a string?

**Comment by zlargon** [comment]
Sorry, I don't have that one. 😅

**Comment by sunsgs** [comment]
any suggestion?

**Comment by zlargon** [comment]
Maybe you can try to integrate with Google speech recognition API.
https://cloud.google.com/speech/
