### ISSUE TITLE
Cors problem

### ISSUE THREAD

**Issue by NashIlli** [zlargon/google-tts#10]
Hi!

I tried to use google-tts in my web app but when I did a request I obtained this error in the console:

`Failed to load https://translate.google.com/: Redirect from 'https://translate.google.com/' to 'https://translate.google.com/m/translate' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by DevJoseWeb** [comment]
Are you using firebase?

**Comment by NashIlli** [comment]
Nop

**Comment by zlargon** [comment]
Hi!

Please refer to this issue https://github.com/zlargon/google-tts/issues/6
Thank you.

Best Regards,
Leon
