### ISSUE TITLE
Male voice

### ISSUE THREAD

**Issue by SeymourSchlong** [zlargon/google-tts#12]
I was wondering if it would be possible for people to choose between a female and male voice (if there is one)

**Comment by zlargon** [comment]
Thank you for the suggestion. However, the Google Translate API doesn't seem to provide this feature, so it is not possible to implement this into the library.

**Comment by Hypnos3** [comment]
there is currently a documentation available:
https://cloud.google.com/text-to-speech/docs/voices

**Comment by zlargon** [comment]
Hi, @Hypnos3 

Thank you for the information. It seems that this feature only enables with paid Google API Key. 🤔

**Comment by Hypnos3** [comment]
yes for the wavenet voices. But the standard voices seems to be free. Therefore it seems that a POST request is needed with an additional name parameter.

**Comment by zlargon** [comment]
Hi, @Hypnos3 

I didn't find the free POST request you mention in the document. Could you please send me the direct link?

I also found this [thread](https://support.google.com/translate/thread/2017149?hl=en) about the male voice from google translate support.

Please let me know if you find an example to request the male voice (without API KEY).
Thank you

**Comment by Hypnos3** [comment]
Sorry, I saw that wrong. There are only different pricing [levels](https://cloud.google.com/text-to-speech/pricing?hl=en).

**Comment by zlargon** [comment]
Hi, @Hypnos3 

Thank you for re-verifying the document. We always want to have a male voice if possible. 😄
