### ISSUE TITLE
Error: get key failed from google in version 0.0.3

### ISSUE THREAD

**Issue by 2Red** [zlargon/google-tts#22]
Hello zlargon,

Currently, I'm using **google-tts-api in** version 0.0.3, and it's no longer working, an "get key failed from google" error appears.
Does it not work in older versions?
Do we need to update to the latest version?

Thank.

**Comment by chohaku84** [comment]
In node_modules/google-home-notifier/package.json,
change 
`"google-tts-api": "0.0.3",` to `"google-tts-api": "0.0.4",`
then update npm
`cd node_modules/google-home-notifier
npm update google-tts-api`

works fine for me.

**Comment by zlargon** [comment]
@chohaku84 Thank you for the reply. 👍
