### ISSUE TITLE
Error: get key failed from google

### ISSUE THREAD

**Issue by otse** [zlargon/google-tts#24]
Hi, this gave me the error

Error: get key failed from google
    at [redacted]\node_modules\google-tts-api\lib\key.js:23:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by zlargon** [comment]
Hi,
Please make sure you update the library to the latest version (0.0.4)
Thank you.

**Comment by sasial-roblox** [comment]
Is this issue fixed?

**Comment by zlargon** [comment]
Yes, it is fixed. Thank you to remind me to close this issue.
