### ISSUE TITLE
Can we use this package in React Native app ?

### ISSUE THREAD

**Issue by nileshprajapati007444** [zlargon/google-tts#26]

**Comment by svrooij** [comment]
Probably. Have you tried it?

**Comment by melounek** [comment]
I am trying to use this repo on client-side, but with error which I don't know if is solve-able:

> Access to fetch at 'https://translate.google.com/' from origin 'http://192.168.0.101:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
