### ISSUE TITLE
SSML possible?

### ISSUE THREAD

**Issue by ozett** [zlargon/google-tts#29]
can i use SSML-Tags to control the tts?
i dont see anything mentioned here...

https://cloud.google.com/text-to-speech/docs/ssml

thx,

**Comment by solyarisoftware** [comment]
Hi @ozett

I agree with @Hypnos3 here:  https://github.com/Hypnos3/node-red-contrib-cast/issues/75#issuecomment-561871642

- zlargon/google-tts uses Google Translate TTS, that is the synthetic voice currently used by Google in Google TRANSLATE web service. This voice is NOT controllable ( a part a minor/immo useless, speed setting ).

- Google Text To Speech is the pay-per-usage Google Cloud Platform service. That's another story.

Now, some/small SSML features, as controlling pauses, could be possible, working on-top of zlargon/google-tts.

BTW, I'm working on https://github.com/solyarisoftware/jointts, a concatenative TTS experiment (that use this package, as an option).  So by example, you can build speech, configuring that a BLANK correspond to some number of millisecond, A FULL_STOP to a bigger value of msecs, etc.

Nevertheless, I fair  it's not worth implementing SSML for such a strict set of features.
My two cents.

**Comment by ozett** [comment]
thx for the link to your github, i will have a look
