### ISSUE TITLE
Randomly stopped working recently.

### ISSUE THREAD

**Issue by sustained** [zlargon/google-tts#3]
Nothing much else to say, I don't have any errors or anything; there aren't any.

Google must have changed something as where this was working before, now it isn't.

**Comment by zlargon** [comment]
I have tested the library on CI server, and it works fine.
For testing, you can also run `npm test` on your own platform.

Please check the test reports on CI server:
- https://travis-ci.org/zlargon/google-tts
- https://ci.appveyor.com/project/zlargon/google-tts

**Comment by sustained** [comment]
Then clearly Google has banned my IP?

I barely even used this much. Are they not banning your IPs?

**Comment by sustained** [comment]
I would say that you need to test this from a VPN provider, like Linode.

Because here's what happened - it worked fine for a week then all of a sudden, it stopped working. And I didn't even change the relevant code, nor did any dependencies change.
