### ISSUE TITLE
Translate long texts

### ISSUE THREAD

**Issue by pavlukivan** [zlargon/google-tts#30]
1. Split text to parts of max 200 chars
2. Add parameters: `q=<part>&total=<total parts>&idx=<part index>&textlen=<part length>`

**Comment by zlargon** [comment]
Version 2.0.0 supports the long texts now. Please see the usage in [README](https://github.com/zlargon/google-tts/blob/master/README.md):

### 3. `getAllAudioUrls(text, [option])` (For text longer than 200 characters)

- Available options: `lang`, `slow`, `host`, `splitPunct`
- Example:
   ```js
   const googleTTS = require('google-tts-api');

   const results = googleTTS.getAllAudioUrls('LONG_TEXT_...', {
     lang: 'en-US',
     slow: false,
     host: 'https://translate.google.com',
     splitPunct: ',.?',
   });
   console.log(results);
   // [
   //   { shortText: '...', url: '...' },
   //   { shortText: '...', url: '...' },
   //   ...
   // ];
   ```

### 4. `getAllAudioBase64(text, [option])` (For text longer than 200 characters)

- This is a promise function
- Available options: `lang`, `slow`, `host`, `timeout`, `splitPunct`
- Example:
   ```js
   const googleTTS = require('google-tts-api');

   googleTTS
     .getAllAudioBase64('LONG_TEXT_...', {
       lang: 'en-US',
       slow: false,
       host: 'https://translate.google.com',
       timeout: 10000,
       splitPunct: ',.?',
     })
     .then(console.log)
     // [
     //   { shortText: '...', base64: '...' },
     //   { shortText: '...', base64: '...' },
     //   ...
     // ];
     .catch(console.error);
   ```
