### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present

### ISSUE THREAD

**Issue by alexey-baranov** [zlargon/google-tts#6]
Not works in Chrome

> Fetch API cannot load https://translate.google.com/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> home.vue:68 TypeError: Failed to fetch

**Comment by zlargon** [comment]
Of course it can't work in Chrome.
This is the library for Node.js (server-side), but not for Browser (client-side).

https://translate.google.com/ do not support "CORS", that why you can't make a cross-origin HTTP request from browsers. It is part of the browser policy.

You can learn more "CORS" from https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
