### ISSUE TITLE
Shouldn't it cache the key for next use?

### ISSUE THREAD

**Issue by xieranmaya** [zlargon/google-tts#7]
I've checked the source code and found the key is requested and computed every time the function is called.

**Comment by zlargon** [comment]
API key is not fixed, and it would change over a period of time.

Of course you can cache and reuse API key if you have a bunch of requests in a short time, but when the key will change is unpredictable.

Please refer these examples which reuse API key:
https://github.com/zlargon/google-tts/blob/master/example/reuse-api-key.js
https://github.com/zlargon/google-tts/blob/master/example/long-english-characters.js
